"""initial schema - all 25 entities

Revision ID: 7c1939c57b4e
Revises: 
Create Date: 2026-03-08 14:09:43.516653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c1939c57b4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('memory_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_tokens_per_call', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('eval_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('eval_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eval_prompt', sa.Text(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('applies_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phase_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gate_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('source_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('implementation_owner_role', sa.String(), nullable=True),
    sa.Column('requires_client_admin', sa.Boolean(), nullable=False),
    sa.Column('client_dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_scope', sa.Text(), nullable=True),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('layers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phase_definition_id', sa.UUID(), nullable=False),
    sa.Column('template_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_format', sa.String(), nullable=False),
    sa.Column('ai_generation_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phase_definition_id'], ['phase_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phase_definition_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('hybrid_pattern', sa.String(), nullable=True),
    sa.Column('default_owner_role', sa.String(), nullable=False),
    sa.Column('secondary_owner_role', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_trust_level', sa.String(), nullable=False),
    sa.Column('default_reminder_hours', sa.Integer(), nullable=False),
    sa.Column('default_max_reminders', sa.Integer(), nullable=False),
    sa.Column('maps_to_document', sa.String(), nullable=True),
    sa.Column('maps_to_gate_item', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phase_definition_id'], ['phase_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_phase_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['current_phase_id'], ['phase_instance.id'], use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_io_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_definition_id', sa.UUID(), nullable=False),
    sa.Column('io_type', sa.String(), nullable=False),
    sa.Column('data_key', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('source_task_definition_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_task_definition_id'], ['task_definition.id'], ),
    sa.ForeignKeyConstraint(['task_definition_id'], ['task_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_project_created', 'audit_log', ['project_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_table('cross_project_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledge_type', sa.String(), nullable=False),
    sa.Column('source_project_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('times_successful', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_user_read', 'notification', ['user_id', 'read'], unique=False)
    op.create_table('phase_instance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase_definition_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gate_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gate_override_by', sa.UUID(), nullable=True),
    sa.Column('gate_override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gate_override_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['phase_definition_id'], ['phase_definition.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_instance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_definition_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_layer', sa.String(), nullable=True),
    sa.Column('pilot_status', sa.String(), nullable=True),
    sa.Column('dev_status', sa.String(), nullable=True),
    sa.Column('prod_status', sa.String(), nullable=True),
    sa.Column('pilot_reviewed_by', sa.UUID(), nullable=True),
    sa.Column('prod_signed_off_by_architect', sa.UUID(), nullable=True),
    sa.Column('prod_signed_off_by_client', sa.UUID(), nullable=True),
    sa.Column('client_credentials_provided', sa.Boolean(), nullable=False),
    sa.Column('client_etl_complete', sa.Boolean(), nullable=False),
    sa.Column('schema_id', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('connection_id', sa.String(), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pilot_reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prod_signed_off_by_architect'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prod_signed_off_by_client'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['source_definition_id'], ['source_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_instance_project_status', 'source_instance', ['project_id', 'status'], unique=False)
    op.create_table('user_project_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'role_id', name='uq_user_project_role')
    )
    op.create_table('task_instance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_definition_id', sa.UUID(), nullable=False),
    sa.Column('phase_instance_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trust_level', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_by', sa.UUID(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parallel_prep_status', sa.String(), nullable=False),
    sa.Column('parallel_prep_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['override_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['phase_instance_id'], ['phase_instance.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_definition_id'], ['task_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_instance_assigned_status', 'task_instance', ['assigned_to', 'status'], unique=False)
    op.create_index('ix_task_instance_phase_instance', 'task_instance', ['phase_instance_id'], unique=False)
    op.create_index('ix_task_instance_project_status', 'task_instance', ['project_id', 'status'], unique=False)
    op.create_table('agent_execution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_definition_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_instance_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools_called', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('eval_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('pause_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_definition_id'], ['agent_definition.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_execution_project_created', 'agent_execution', ['project_id', 'created_at'], unique=False, postgresql_using='btree')
    op.create_table('ai_question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase_instance_id', sa.UUID(), nullable=False),
    sa.Column('task_instance_id', sa.UUID(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('question_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('maps_to_document_field', sa.String(), nullable=True),
    sa.Column('maps_to_gate_item', sa.String(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.UUID(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answered_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['phase_instance_id'], ['phase_instance.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_question_target_role_status', 'ai_question', ['target_role', 'status'], unique=False)
    op.create_table('document_instance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_template_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase_instance_id', sa.UUID(), nullable=False),
    sa.Column('task_instance_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_template_id'], ['document_template.id'], ),
    sa.ForeignKeyConstraint(['phase_instance_id'], ['phase_instance.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_io_instance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_io_definition_id', sa.UUID(), nullable=False),
    sa.Column('task_instance_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('produced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ),
    sa.ForeignKeyConstraint(['task_io_definition_id'], ['task_io_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('phase_instance_id', sa.UUID(), nullable=True),
    sa.Column('task_instance_id', sa.UUID(), nullable=True),
    sa.Column('agent_execution_id', sa.UUID(), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('is_rework', sa.Boolean(), nullable=False),
    sa.Column('rework_reason', sa.String(), nullable=True),
    sa.Column('is_eval', sa.Boolean(), nullable=False),
    sa.Column('eval_definition_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_execution.id'], ),
    sa.ForeignKeyConstraint(['eval_definition_id'], ['eval_definition.id'], ),
    sa.ForeignKeyConstraint(['phase_instance_id'], ['phase_instance.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_tracking_project_phase', 'cost_tracking', ['project_id', 'phase_instance_id'], unique=False)
    op.create_table('eval_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eval_definition_id', sa.UUID(), nullable=False),
    sa.Column('agent_execution_id', sa.UUID(), nullable=False),
    sa.Column('task_instance_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eval_tokens_used', sa.Integer(), nullable=False),
    sa.Column('eval_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_execution.id'], ),
    sa.ForeignKeyConstraint(['eval_definition_id'], ['eval_definition.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_execution_id', sa.UUID(), nullable=False),
    sa.Column('task_instance_id', sa.UUID(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('corrected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_execution.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_project_category', 'feedback', ['project_id', 'category'], unique=False)
    op.create_table('improvement_proposal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('generated_by_agent_execution_id', sa.UUID(), nullable=False),
    sa.Column('proposal_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_agent_execution_id'], ['agent_execution.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('improvement_proposal')
    op.drop_index('ix_feedback_project_category', table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('eval_result')
    op.drop_index('ix_cost_tracking_project_phase', table_name='cost_tracking')
    op.drop_table('cost_tracking')
    op.drop_table('task_io_instance')
    op.drop_table('document_instance')
    op.drop_index('ix_ai_question_target_role_status', table_name='ai_question')
    op.drop_table('ai_question')
    op.drop_index('ix_agent_execution_project_created', table_name='agent_execution', postgresql_using='btree')
    op.drop_table('agent_execution')
    op.drop_index('ix_task_instance_project_status', table_name='task_instance')
    op.drop_index('ix_task_instance_phase_instance', table_name='task_instance')
    op.drop_index('ix_task_instance_assigned_status', table_name='task_instance')
    op.drop_table('task_instance')
    op.drop_table('user_project_role')
    op.drop_index('ix_source_instance_project_status', table_name='source_instance')
    op.drop_table('source_instance')
    op.drop_table('phase_instance')
    op.drop_index('ix_notification_user_read', table_name='notification')
    op.drop_table('notification')
    op.drop_table('cross_project_knowledge')
    op.drop_index('ix_audit_log_project_created', table_name='audit_log', postgresql_using='btree')
    op.drop_table('audit_log')
    op.drop_table('task_io_definition')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('task_definition')
    op.drop_table('document_template')
    op.drop_table('source_definition')
    op.drop_table('role')
    op.drop_table('phase_definition')
    op.drop_table('organization')
    op.drop_table('eval_definition')
    op.drop_table('agent_definition')
    # ### end Alembic commands ###
