import { useOutletContext } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { listDocumentTemplates, listProjectDocuments, createDocument, reviewDocument } from '../api/endpoints';
import StatusBadge from '../components/StatusBadge';
import { FileText, Plus, Check, X } from 'lucide-react';

export default function DocumentsTab() {
  const { projectId, project } = useOutletContext<any>();
  const qc = useQueryClient();

  const { data: templates } = useQuery({
    queryKey: ['doc-templates'],
    queryFn: () => listDocumentTemplates().then((r) => r.data),
  });

  const { data: documents } = useQuery({
    queryKey: ['project-docs', projectId],
    queryFn: () => listProjectDocuments(projectId).then((r) => r.data),
  });

  const createMut = useMutation({
    mutationFn: (templateId: string) =>
      createDocument({
        document_template_id: templateId,
        project_id: projectId,
        phase_instance_id: project.current_phase_id,
      }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['project-docs'] }),
  });

  const reviewMut = useMutation({
    mutationFn: ({ id, approved }: { id: string; approved: boolean }) => reviewDocument(id, { approved }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['project-docs'] }),
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-slate-900">Documents</h2>
      </div>

      {/* Templates */}
      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <h3 className="text-sm font-semibold text-slate-700 mb-3">Generate from Template</h3>
        <div className="flex flex-wrap gap-2">
          {templates?.map((t: any) => (
            <button
              key={t.id}
              onClick={() => createMut.mutate(t.id)}
              disabled={createMut.isPending}
              className="flex items-center gap-1.5 border border-slate-200 text-slate-700 px-3 py-1.5 rounded-lg text-sm hover:bg-slate-50"
            >
              <Plus size={14} /> {t.name} ({t.output_format})
            </button>
          ))}
        </div>
      </div>

      {/* Document instances */}
      <div className="space-y-3">
        {documents?.map((doc: any) => {
          const tmpl = templates?.find((t: any) => t.id === doc.document_template_id);
          return (
            <div key={doc.id} className="bg-white rounded-xl border border-slate-200 p-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileText size={16} className="text-blue-500" />
                  <span className="font-medium text-slate-900">{tmpl?.name || 'Document'}</span>
                  <span className="text-xs text-slate-400">v{doc.version}</span>
                </div>
                <div className="flex items-center gap-2">
                  <StatusBadge status={doc.status} />
                  {(doc.status === 'DRAFT' || doc.status === 'IN_REVIEW') && (
                    <>
                      <button
                        onClick={() => reviewMut.mutate({ id: doc.id, approved: true })}
                        className="p-1 rounded hover:bg-green-50 text-green-600"
                        title="Approve"
                      >
                        <Check size={16} />
                      </button>
                      <button
                        onClick={() => reviewMut.mutate({ id: doc.id, approved: false })}
                        className="p-1 rounded hover:bg-red-50 text-red-600"
                        title="Request Revision"
                      >
                        <X size={16} />
                      </button>
                    </>
                  )}
                </div>
              </div>
              <div className="mt-2 text-xs text-slate-500">
                Generated by: {doc.generated_by} | Created: {new Date(doc.created_at).toLocaleString()}
              </div>
            </div>
          );
        })}
        {(!documents || documents.length === 0) && (
          <div className="text-center py-8 text-slate-400 text-sm">No documents generated yet.</div>
        )}
      </div>
    </div>
  );
}
